
on:
  push:
    branches:
      - master




jobs:
  bulid: 
    runs-on: ubuntu-latest
    
    
    steps:
      - name: "just dream"
        run: ls
      
      - uses: actions/checkout@v3
      
      - name: "you can"
        run: ls





