
on:
  push:
    branches:
      - master




jobs:
  bulid: 
    run-on: ubuntu-latest

    steps:
      - name: "just dream"
        run: ls
      
      - user: actions/checkout@v3
      
      - name : "you can"
        run : ls





